## Importing packages

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

## Load Dataset

In [3]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

## Preprocessing

In [4]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

## Encode categorical variables

In [6]:
LE_gender=LabelEncoder()
data['Gender']=LE_gender.fit_transform(data['Gender'])

In [7]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

### One_hot _encoding on 'Geography' column

In [16]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder_geo=OneHotEncoder(sparse_output=False)

In [17]:
geo_encoder=onehotencoder_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [18]:
onehotencoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [19]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehotencoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [20]:
data=pd.concat([(data.drop('Geography',axis=1)),geo_encoded_df],axis=1)

In [21]:
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        10000 non-null  int64
 1   Gender             10000 non-null  int32
 2   Age                10000 non-null  int64
 3   Tenure             10000 non-null  int64
 4   Balance            10000 non-null  float64
 5   NumOfProducts      10000 non-null  int64
 6   HasCrCard          10000 non-null  int64
 7   IsActiveMember     10000 non-null  int64
 8   EstimatedSalary    10000 non-null  float64
 9   Exited             10000 non-null  int64
 10  Geography_France   10000 non-null  float64
 11  Geography_Germany  10000 non-null  float64
 12  Geography_Spain    10000 non-null  float64
dtypes: float64(5), int32(1), int64(7)
memory usage: 976.7 KB

### Save the Encoders

In [24]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(LE_gender,file)

with open('One_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehotencoder_geo,file)

## Dividing independent and dependent Features

In [25]:
X=data.drop('Exited',axis=1)
y=data['Exited']

### Spliting train and test data

In [26]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [28]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [29]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [30]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [31]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

# ANN implementation

In [32]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [36]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')

]
)

WARNING:tensorflow:From c:\Users\saiva\vs code\Current_Learning\Ds ML bootcamp\Work space\self_Projects\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
opti=tf.keras.optimizers.Adam(learning_rate=0.01)

In [40]:
model.compile(optimizer=opti,loss='binary_crossentropy',metrics=['accuracy'])

In [62]:
## set up the tensor board
log_dir="logs/fit"
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [44]:
## set up of Early stopping
early_Stopping=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

## training the model

In [45]:
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[tensorflow_callback,early_Stopping])

Epoch 1/100
WARNING:tensorflow:From c:\Users\saiva\vs code\Current_Learning\Ds ML bootcamp\Work space\self_Projects\ANN Classification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\saiva\vs code\Current_Learning\Ds ML bootcamp\Work space\self_Projects\ANN Classification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 2ms/step - loss: 0.3930 - accuracy: 0.8347 - val_loss: 0.3488 - val_accuracy: 0.8600
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3524 - accuracy: 0.8579 - val_loss: 0.3595 - val_accuracy: 0.8590
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3466 - accuracy: 0.8599 - val_loss: 0.3492 - val_accuracy: 0.8550
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3460 - accuracy: 0.8585 - val_loss: 0.3451 - val_accuracy: 0.8575
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3405 - accuracy: 0.8589 - val_loss: 0.3462 - val_accuracy: 0.8605
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3380 - accuracy: 0.8621 - val_loss: 0.3365 - val_accuracy: 0.8610
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3347 - accuracy: 0.8605 - val_loss: 0.3492 - val_accuracy: 0.8570
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8614 - val_loss: 0.3381 - val_accuracy: 0.8605
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8619 - val_loss: 0.3450 - val_accuracy: 0.8590
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8661 - val_loss: 0.3465 - val_accuracy: 0.8610
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3269 - accuracy: 0.8665 - val_loss: 0.3601 - val_accuracy: 0.8585
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.8681 - val_loss: 0.3488 - val_accuracy: 0.8605
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3246 - accuracy: 0.8639 - val_loss: 0.3468 - val_accuracy: 0.8645
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3231 - accuracy: 0.8662 - val_loss: 0.3504 - val_accuracy: 0.8595
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3233 - accuracy: 0.8649 - val_loss: 0.3370 - val_accuracy: 0.8620
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3193 - accuracy: 0.8700 - val_loss: 0.3465 - val_accuracy: 0.8615

In [46]:
model.save('model.h5')

c:\Users\saiva\vs code\Current_Learning\Ds ML bootcamp\Work space\self_Projects\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [59]:
## load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [60]:
%reload_ext tensorboard

In [61]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 12340), started 0:00:55 ago. (Use '!kill 12340' to kill it.)